baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Members'
pageRef = ''
weight = 20

[[menus.main]]
name = 'Projects'
pageRef = ''
weight = 20

[[menus.main]]
name = 'Events'
pageRef = ''
weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
